#TODO: libwayland native build done, needs libinput for full input support
[source]
git = "https://github.com/jackpot51/smithay"
branch = "redox"

[build]
template = "cargo"
dependencies = [
    "libevdev",
    "libffi",
    "libinput",
    "libwayland",
    "libxkbcommon",
]
cargopackages = [
    "smallvil"
]
