[source]
git = "https://gitlab.redox-os.org/redox-os/redoxfs.git"
patches = ["P2-readonly-live-media-open.patch"]

[build]
template = "custom"
script = """
# Must be statically linked
cookbook_cargo
"""
