[source]
path = "source"

[build]
template = "custom"
script = """
set -ex

cookbook_cargo

mkdir -pv "$COOKBOOK_STAGE/usr/lib/init.d"
cp -v "$COOKBOOK_SOURCE/11_btctl.service" "$COOKBOOK_STAGE/usr/lib/init.d/11_btctl.service"
"""
