[source]
path = "source"

[build]
template = "cargo"

[package.files]
"/usr/bin/lspci" = "lspci"
"/usr/bin/lsusb" = "lsusb"
"/usr/bin/redbear-usb-check" = "redbear-usb-check"
"/usr/bin/redbear-bluetooth-battery-check" = "redbear-bluetooth-battery-check"
"/usr/bin/redbear-drm-display-check" = "redbear-drm-display-check"
"/usr/bin/redbear-phase4-wayland-check" = "redbear-phase4-wayland-check"
"/usr/bin/redbear-phase5-network-check" = "redbear-phase5-network-check"
"/usr/bin/redbear-phase5-wifi-check" = "redbear-phase5-wifi-check"
"/usr/bin/redbear-phase5-wifi-capture" = "redbear-phase5-wifi-capture"
"/usr/bin/redbear-phase5-wifi-run" = "redbear-phase5-wifi-run"
"/usr/bin/redbear-phase5-wifi-analyze" = "redbear-phase5-wifi-analyze"
"/usr/bin/redbear-phase5-wifi-link-check" = "redbear-phase5-wifi-link-check"
