[source]
path = "source"

[build]
template = "custom"
script = """
set -ex

cookbook_cargo

mkdir -pv "$COOKBOOK_STAGE/usr/lib/init.d"
cp -v "$COOKBOOK_SOURCE/10_btusb.service" "$COOKBOOK_STAGE/usr/lib/init.d/10_btusb.service"
"""
