[source]
same_as = "../../../libs/mesa"

[build]
template = "custom"
dependencies = [
    "expat",
    "libdrm",
    "libx11",
    "libxcb",
    "libxext",
    "libxfixes",
    "libxrandr",
    "libxshmfence",
    "libxxf86vm",
    "llvm21",
    "zlib",
]
dev-dependencies = [
    "llvm21.dev",
]

script = """
DYNAMIC_INIT

export CFLAGS+=" -DHAVE_PTHREAD=1 -I${COOKBOOK_SYSROOT}/include/libdrm"
export LLVM_CONFIG="${TARGET}-llvm-config"
if [ -x "${HOME}/.redoxer/${TARGET}/toolchain/bin/llvm-config" ]; then
    export COOKBOOK_HOST_SYSROOT="${HOME}/.redoxer/${TARGET}/toolchain"
fi

mkdir -p .cookbook-tools
ln -sf "$(command -v "${LLVM_CONFIG}")" .cookbook-tools/llvm-config
export PATH="$(pwd)/.cookbook-tools:${PATH}"

if [ "${COOKBOOK_DYNAMIC}" == "1" ]; then
    COOKBOOK_MESON_FLAGS+=(-Dshared-llvm=enabled)
else
    COOKBOOK_MESON_FLAGS+=(-Dshared-llvm=disabled)
fi

cookbook_meson \
    -Ddri-drivers-path=/usr/lib/dri \
    -Degl=enabled \
    -Dglx=dri \
    -Dllvm=enabled \
    -Dplatforms=x11 \
    -Dshader-cache=disabled
"""
