[source]
path = "source"
patches = ["../../../../local/patches/redbear-sessiond/P4-signal-implementations.patch"]

[build]
template = "cargo"
dependencies = ["dbus"]

[package.files]
"/usr/bin/redbear-sessiond" = "redbear-sessiond"
