# Configuration for "acid" testing

include = ["base.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 1024

# Package settings
[packages]
acid = {}
coreutils = {}
ion = {}

[[files]]
path = "/usr/lib/init.d/10_acid.service"
data = """
[unit]
description = "Acid test runner"
requires_weak = ["00_pcid-spawner.service"]

[service]
cmd = "ion"
args = ["/usr/lib/run_acid.ion"]
type = "oneshot_async"
"""

[[files]]
path = "/usr/lib/run_acid.ion"
data = """
#!/usr/bin/env ion
export RUST_BACKTRACE=full
cd /home/user/acid
cargo test
shutdown
"""
