# Configuration for "os-test" testing

include = ["server.toml"]

# General settings
[general]
# Filesystem size in MiB
filesystem_size = 1024
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
os-test-bins = {} # Provides source and cross-compiled binaries

[[files]]
path = "/usr/lib/init.d/30_console.service"
data = """
[unit]
description = "OS test runner"
requires_weak = ["00_base.target"]

[service]
cmd = "ion"
args = ["-c", "os-test-runner; shutdown"]
envs = { RUST_BACKTRACE = "full" }
type = "oneshot"
"""
