# Red Bear OS overrides for broken legacy base init scripts.

[[files]]
path = "/usr/lib/init.d/00_base"
data = ""

[[files]]
path = "/usr/lib/init.d/00_drivers"
data = ""

[[files]]
path = "/usr/lib/init.d/10_net"
data = ""

[[files]]
path = "/etc/init.d/20_audiod.service"
data = """
[unit]
description = "Audio multiplexer"
default_dependencies = false

[service]
cmd = "audiod"
type = "oneshot_async"
"""
