# Configuration for the Redoxer GUI image

include = ["redoxer.toml"]

# Package settings
[packages]
orbdata = {}
orbital = {}

# Override to run inside of orbital
[[files]]
path = "/usr/lib/init.d/30_redoxer.service"
data = """
[unit]
description = "Redoxer GUI test (orbital)"
requires_weak = ["10_dhcpd.service"]

[service]
cmd = "orbital"
args = ["redoxerd"]
envs = { VT = "3" }
type = "oneshot_async"
"""
