[source]
git = "https://gitlab.redox-os.org/redox-os/relibc.git"
patches = [
    "../../../local/patches/relibc/redox.patch",
    "../../../local/patches/relibc/P0-strtold-cpp-linkage-and-compat.patch",
    "../../../local/patches/relibc/P3-signalfd.patch",
    "../../../local/patches/relibc/P3-signalfd-header.patch",
    "../../../local/patches/relibc/P3-timerfd.patch",
    "../../../local/patches/relibc/P3-waitid.patch",
    "../../../local/patches/relibc/P3-semaphore-fixes.patch",
    "../../../local/patches/relibc/P3-socket-cred.patch",
    "../../../local/patches/relibc/P3-elf64-types.patch",
    "../../../local/patches/relibc/P3-open-memstream.patch",
    "../../../local/patches/relibc/P3-ifaddrs-net_if.patch",
    "../../../local/patches/relibc/P3-fd-event-tests.patch",
    "../../../local/patches/relibc/P3-eventfd-mod.patch",
    "../../../local/patches/relibc/P3-netdb-lookup-retry-fix.patch",
    "../../../local/patches/relibc/P3-exec-root-bypass.patch",
    "../../../local/patches/relibc/P3-tcp-nodelay.patch",
    "../../../local/patches/relibc/P3-select-not-epoll-timeout.patch",
    "../../../local/patches/relibc/P3-tls-get-addr-panic-fix.patch",
    "../../../local/patches/relibc/P3-pthread-yield.patch",
    "../../../local/patches/relibc/P3-secure-getenv.patch",
    "../../../local/patches/relibc/P3-getentropy.patch",
    "../../../local/patches/relibc/P3-dup3.patch",
    "../../../local/patches/relibc/P3-vfork.patch",
    "../../../local/patches/relibc/P3-clock-nanosleep.patch",
    "../../../local/patches/relibc/P3-named-semaphores.patch",
    "../../../local/patches/relibc/P3-fcntl-dupfd-cloexec.patch",
    "../../../local/patches/relibc/P3-ipc-tests.patch",
    "../../../local/patches/relibc/P3-socket-flags.patch",
    "../../../local/patches/relibc/P3-syscall-0.7.4-procschemeattrs-ens-to-prio.patch",
    "../../../local/patches/relibc/P3-sysv-ipc.patch",
    "../../../local/patches/relibc/P3-sysv-sem-impl.patch",
    "../../../local/patches/relibc/P3-sysv-shm-impl.patch",
    "../../../local/patches/relibc/P3-waitid-header.patch",
]

[build]
template = "custom"
script = """
# rustup workaround https://github.com/rust-lang/rustup/issues/988
if [ "${COOKBOOK_HOST_SYSROOT}" = "/usr" ] && command -v rustup >/dev/null 2>&1; then
    pushd ${COOKBOOK_SOURCE}
    ${RUSTUP:-rustup} install
    popd
fi

export CARGO=${CARGO:-env -u CARGO cargo}
"${COOKBOOK_MAKE}" \
    -C "${COOKBOOK_SOURCE}" \
    -j"${COOKBOOK_MAKE_JOBS}" \
    DESTDIR="${COOKBOOK_STAGE}/usr" \
    install
"""
