#TODO: historical bounded validation compositor reference only; no longer part of the active forward desktop workflow
[source]
git = "https://github.com/jackpot51/smithay"
branch = "redox"

[build]
template = "cargo"
dependencies = [
    "libevdev",
    "libffi",
    "libinput",
    "libwayland",
    "libxkbcommon",
]
cargopackages = [
    "smallvil"
]
